CREATE TABLE "APPEARANCE" (
	"ACTOR_ID"	VARCHAR2(18CHAR)		NOT NULL,
	"ACTOR_NAME"	VARCHAR2(25 CHAR)		NOT NULL,
	"ACTOR_PROFILE_URL"	VARCHAR2(2048 CHAR)		NOT NULL
);

COMMENT ON COLUMN "APPEARANCE"."ACTOR_ID" IS 'AC-YYYYMMDD일련번호(6자리)';

CREATE TABLE "ACTOR" (
	"APPEARANCE_ID"	VARCHAR2(18CHAR)		NOT NULL,
	"MOVIE_ID"	VARCHAR2(18 CHAR)		NOT NULL,
	"ACTOR_ID"	VARCHAR2(18CHAR)		NOT NULL,
	"CHARACTER"	VARCHAR2(40 CHAR)		NULL
);

COMMENT ON COLUMN "ACTOR"."APPEARANCE_ID" IS 'AP-YYYYMMDD일련번호(6자리)';

COMMENT ON COLUMN "ACTOR"."MOVIE_ID" IS 'MV-YYYYMMDD일련번호(6자리)';

COMMENT ON COLUMN "ACTOR"."ACTOR_ID" IS 'AC-YYYYMMDD일련번호(6자리)';

CREATE TABLE "MAKE" (
	"MAKE_ID"	VARCHAR2(18CHAR)		NOT NULL,
	"PRODUCER_ID"	VARCHAR2(18CHAR)		NOT NULL,
	"MOVIE_ID"	VARCHAR2(18 CHAR)		NOT NULL,
	"ROLE"	VARCHAR2(25 CHAR)		NOT NULL,
	"PART"	VARCHAR2(10CHAR)		NULL
);

COMMENT ON COLUMN "MAKE"."MAKE_ID" IS 'MK-YYYYMMDD일련번호(6자리)';

COMMENT ON COLUMN "MAKE"."PRODUCER_ID" IS 'PD-YYYYMMDD일련번호(6자리)';

COMMENT ON COLUMN "MAKE"."MOVIE_ID" IS 'MV-YYYYMMDD일련번호(6자리)';

CREATE TABLE "PRODUCER" (
	"PRODUCER_ID"	VARCHAR2(18CHAR)		NOT NULL,
	"PRODUCER_NAME"	VARCHAR2(25 CHAR)		NOT NULL
);

COMMENT ON COLUMN "PRODUCER"."PRODUCER_ID" IS 'PD-YYYYMMDD일련번호(6자리)';

CREATE TABLE "GENRE" (
	"GENRE_ID"	VARCHAR2(18CHAR)		NOT NULL,
	"MOVIE_ID"	VARCHAR2(18 CHAR)		NOT NULL,
	"CATEGORY_ID"	VARCHAR2(18CHAR)		NOT NULL
);

COMMENT ON COLUMN "GENRE"."GENRE_ID" IS 'GN-YYYYMMDD일련번호(6자리)';

COMMENT ON COLUMN "GENRE"."MOVIE_ID" IS 'MV-YYYYMMDD일련번호(6자리)';

COMMENT ON COLUMN "GENRE"."CATEGORY_ID" IS 'CT-YYYYMMDD일련번호(6자리)';

CREATE TABLE "CATEGORY" (
	"CATEGORY_ID"	VARCHAR2(18CHAR)		NOT NULL,
	"CATEGORY_NAME"	VARCHAR2(10 CHAR)		NOT NULL
);

COMMENT ON COLUMN "CATEGORY"."CATEGORY_ID" IS 'CT-YYYYMMDD일련번호(6자리)';

CREATE TABLE "MOVIE" (
	"MOVIE_ID"	VARCHAR2(18 CHAR)		NOT NULL,
	"POSTER_URL"	VARCHAR2(2048 CHAR)		NOT NULL,
	"TITLE"	VARCHAR2(50 CHAR)		NOT NULL,
	"MOVIE_RATING"	VARCHAR2(3 CHAR)		NULL,
	"OPEN_DATE"	DATE		NULL,
	"OPEN_COUNTRY"	VARCHAR2(2 CHAR)		NULL,
	"RUNNING_TIME"	NUMBER(4, 0)		NULL,
	"INTRODUCE"	VARCHAR2(60 CHAR)		NULL,
	"SYNOPIS"	VARCHAR2(400 CHAR)		NOT NULL,
	"ORIGINAL_TITLE"	VARCHAR2(50 CHAR)		NULL,
	"STATE"	VARCHAR2(5 CHAR)		NOT NULL,
	"LANGUAGE"	VARCHAR2(6 CHAR)		NOT NULL,
	"BUDGET"	NUMBER(11,2)		NULL,
	"PROFIT"	NUMBER(12, 2)		NULL
);

COMMENT ON COLUMN "MOVIE"."MOVIE_ID" IS 'MV-YYYYMMDD일련번호(6자리)';

COMMENT ON COLUMN "MOVIE"."POSTER_URL" IS '대표 포스터의 URL을 작성, 이미지의 크기는 100 X 300';

ALTER TABLE "APPEARANCE" ADD CONSTRAINT "PK_APPEARANCE" PRIMARY KEY (
	"ACTOR_ID"
);

ALTER TABLE "ACTOR" ADD CONSTRAINT "PK_ACTOR" PRIMARY KEY (
	"APPEARANCE_ID"
);

ALTER TABLE "MAKE" ADD CONSTRAINT "PK_MAKE" PRIMARY KEY (
	"MAKE_ID"
);

ALTER TABLE "PRODUCER" ADD CONSTRAINT "PK_PRODUCER" PRIMARY KEY (
	"PRODUCER_ID"
);

ALTER TABLE "GENRE" ADD CONSTRAINT "PK_GENRE" PRIMARY KEY (
	"GENRE_ID"
);

ALTER TABLE "CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY (
	"CATEGORY_ID"
);

ALTER TABLE "MOVIE" ADD CONSTRAINT "PK_MOVIE" PRIMARY KEY (
	"MOVIE_ID"
);

